# .github/workflows/deploy.yml
name: Deploy to Reg.ru via FTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Create set_permissions script
      run: |
        cat > set_permissions.sh << 'EOF'
        #!/bin/bash
        echo "Setting file permissions..."
        find . -type d -exec chmod 755 {} \;
        find . -type f -exec chmod 644 {} \;
        find . -name ".env" -exec chmod 600 {} \;
        find . -name ".htaccess" -exec chmod 644 {} \;
        echo "Permissions set successfully"
        EOF
        chmod +x set_permissions.sh
        mv set_permissions.sh dist/

    - name: List dist contents
      run: ls -la dist/

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.REGRU_FTP_HOST }}
        username: ${{ secrets.REGRU_FTP_USER }}
        password: ${{ secrets.REGRU_FTP_PASSWORD }}
        server-dir: ${{ secrets.REGRU_FTP_REMOTE_PATH }}
        local-dir: ./dist/
        port: ${{ secrets.REGRU_FTP_PORT }}
        protocol: ftp
        exclude: |
          .git*
          .env*
          node_modules/
          *.md
          README*
          LICENSE*
          .editorconfig
          .gitattributes
          .github/
          .gitignore
          .vite/
          vite.config.js
          postcss.config.js
          tailwind.config.js
        dangerous-clean-slate: true

    - name: Notify about permissions script
      run: |
        echo "A set_permissions.sh script has been uploaded to the server."
        echo "Please run it manually via SSH or ask your hosting provider to set correct permissions."