# 6. Шаг: Загрузка файлов на FTP-сервер
- name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ${{ secrets.REGRU_FTP_HOST }}
    username: ${{ secrets.REGRU_FTP_USER }}
    password: ${{ secrets.REGRU_FTP_PASSWORD }}
    server-dir: ${{ secrets.REGRU_FTP_REMOTE_PATH }}
    local-dir: ./dist/
    port: ${{ secrets.REGRU_FTP_PORT }}
    protocol: ftp
    exclude: |
      .git*
      .env*
      node_modules/
      *.md
      README*
      LICENSE*
      .editorconfig
      .gitattributes
      .github/
      .gitignore
      .vite/
      vite.config.js
      postcss.config.js
      tailwind.config.js
    # --- Исправленные/обновленные настройки ---
    # security: strict # Можно раскомментировать, если нужно явно указать
    dangerous-clean-slate: true # Перезаписывать файлы
    # dry-run: true # Раскомментируйте для тестового запуска без реальной загрузки